### PR TITLE
add Swift 2.3 support

### PR DESCRIPTION
**Pull request by macbaszii**
[WIP]

### CODE REVIEW

**Comment by pitiphong-p** [comment]
This is a WIP right?

**Comment by macbaszii** [comment]
@pitiphong-p yes, I haven't fixed the test target yet. Do you wanna join ? please.

**Comment by pitiphong-p** [comment]
No need to update the source file?

**Comment by macbaszii** [comment]
@pitiphong-p yeah, I think all source files is compatible with Swift 2.2

**Comment by pitiphong-p** [comment]
@macbaszii Thank you, I will take a look when I can and feel free to ping me if you have any update on this :)

**Comment by macbaszii** [comment]
I found wired error when I was fixing test target.
Because It's using same public key, one case that's using closure is pass.
the one's using delegate cannot passed that test case.

cc @pitiphong-p 

screen shot 2559-09-27 at 9 56 45 pm

**Comment by pitiphong-p** [comment]
This error caused by the invalid public key was used to create a charge

**Comment by pitiphong-p** [comment]
@macbaszii Do you still need the Swift 2.3 support? Xcode will end support for Swift 2.3 soon so I recommend you to do a migration ASAP

**Pull request closed without merging**
