### PR TITLE
Support OCBC Digital

### PR DESCRIPTION
**Pull request by vault087**

### CODE REVIEW

**Review by nuxzero — APPROVED** [review]
Could you test the authorizing payment to ensure it can handle the custom URL scheme from `authorize_uri`?

**Review by aashishgurung — APPROVED** [review]

**Review by AnasNaouchi — COMMENTED** [review]
Can you add tests for OCBC DIGITAL please ?

**Comment by danfowler** [comment]
@vault087 we might want to adjust the trigger for Sonarcloud to be able to get test coverage metrics for branches not off `master`

**Comment by vault087** [comment]
> Could you test the authorizing payment to ensure it can handle the custom URL scheme from `authorize_uri`?
authorize_uri supports web links that opens in webview and if custom scheme is provided SDK tries to open external app

**Comment by vault087** [comment]
> Can you add tests for OCBC DIGITAL please ?
Payment Information unit tests were restored and added new one for OCBC Digital

**Pull request merged**
