### PR TITLE
[APM2-120] Add mobile banking Kbank menu

### PR DESCRIPTION
**Pull request by nimitomise**
Add mobile banking KBank payment method
Simulator Screen Shot - iPod touch (7th generation) - 2021-11-04 at 16 12 23

Simulator Screen Shot - iPod touch (7th generation) - 2021-11-04 at 16 46 55

### CODE REVIEW

**Comment by kan98** [comment]
I'm not sure if you should provide Thai translations for the bank names?

**Comment by kan98** [comment]
might be useful to add the mobile banking kbank to `OmiseSDKTests/Fixtures/objects/capability.json`, so we can test capability fetches information correctly from it.

**Comment by nimitomise** [comment]
> I'm not sure if you should provide Thai translations for the bank names?

add [here](https://github.com/omise/omise-ios/pull/149/commits/619b272d4ab5cbcd5c2507b9a36d86415629b401) but actually don't know hot to test this in ExampleApp

**Comment by nimitomise** [comment]
> might be useful to add the mobile banking kbank to `OmiseSDKTests/Fixtures/objects/capability.json`, so we can test capability fetches information correctly from it.

add [here](https://github.com/omise/omise-ios/pull/149/commits/5829f0aa18238a71fa19e57db051a46275f5323c) along with unit test

**Review by tookaa2 — APPROVED** [review]

**Review by tobias90 — APPROVED** [review]

**Pull request merged**
